name: Compile Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Dummy step
      run: echo "Setup not needed, because the docker image is built anyway in each job..."

  check-codestyle-and-static:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Check codestyle
      uses: ./.github/actions/exec-in-build-image
      with:
        cmd: ci/check_codestyle.sh
    - name: Static code analysis
      uses: ./.github/actions/exec-in-build-image
      with:
        cmd: ci/static_code_analysis.sh

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build for esp32
      uses: ./.github/actions/exec-in-build-image
      with:
        cmd: ci/build_for_esp32.sh
    - name: Build for PC
      uses: ./.github/actions/exec-in-build-image
      with:
        cmd: ci/build_for_pc.sh
